### ISSUE TITLE
Fix the Heroku site

### ISSUE THREAD

**Issue by ANDREYDEN** [ilovedasha/space-app#2]
Launch the app with Heroku hosting. Fix the errors and make sure it runs independantly.

**Comment by ANDREYDEN** [comment]
The [site](https://launch-io.herokuapp.com/) is currently available, but unstable

**Comment by silverkip** [comment]
Implemented a fix for this issue. Check out #5

**Comment by ANDREYDEN** [comment]
Thank you, is [your](https://spaceappt.herokuapp.com/) site linked to your local repo or the github one?

**Comment by silverkip** [comment]
It was linked to my fork specifically this branch
https://github.com/silverkip/space-app/tree/fix-heroku

**Comment by ANDREYDEN** [comment]
Ok, so can you link it to the main repo (https://github.com/lyova-potyomkin/space-app) or give instructions for how to launch a new Heroku instance?

**Comment by silverkip** [comment]
This is how I did it
1. Create app instance
2. On Deployment screen, Deploy through GitHub (I'll assume your Heroku acc is connected to your GitHub) and input your repo name, in this case it'd be space-app
3. Click search and connect to the repo.
4. Then I manually deploy the branch at the "Manual Deploy" section. Automatic Deployment also works and it updates everytime new commits are pushed to "master"

**Comment by ANDREYDEN** [comment]
ok, so only the owner of the repo can launch it, so we'll wait for @lyova-potyomkin to do that.

**Comment by silverkip** [comment]
Yeah, I think you can try fork a copy of the current master repo for now and test it yourself. I figured the repo was missing the Procfile that tells Heroku what to do. Also requirements.txt to install all required modules (via pip for Python) and runtime.txt telling which programming language and which version is required.

Referenced from these documentations https://devcenter.heroku.com/articles/getting-started-with-python

**Comment by ANDREYDEN** [comment]
Yeah, thanks for adding that

**Comment by ANDREYDEN** [comment]
I'm closing this issue, as the app runs stable on Heroku's free tire. If there's a delay in loading the page, then that is because of the way free Heroku dyno works ([more here](https://devcenter.heroku.com/articles/free-dyno-hours))
