### ISSUE TITLE
Timer fix

### ISSUE THREAD

**Issue by ANDREYDEN** [ilovedasha/space-app#4]
Timer doesn't work correctly: minutes do not decrement, when a minute passes.

**Comment by silverkip** [comment]
![image](https://user-images.githubusercontent.com/46242446/50622266-6b0e5080-0f3e-11e9-8237-aaefb0580021.png)
It's still weird, I thought the time calculation was fixed but both the website and my test run were showing different results. I print them on an interval of 1 second. The website displayed 3 days 2 hours 46 mins remaining as opposed to the 3 days 18 hours 51mins from my isolated test run. (Without HTML. Just the .py snippet)

UPDATE : I hosted the entire script on localhost with the latest build and found no problem whatsoever with the timer (everything working fine) and also with the correct "Time Until Launch". I suspect something is wrong on heroku's side. I'll see what I can dig.

**Comment by ANDREYDEN** [comment]
I think the problem is that the timer is time zone sensitive... That explains the difference between the local timer and the one on Heroku

**Comment by silverkip** [comment]
The branch I deployed on my Heroku account worked as intended though. So I guess you can give it a shot.

**Comment by ANDREYDEN** [comment]
Thank you, your timer works perfectly indeed
